[package]
name = "utils"
version = "0.1.0"
authors = ["huzecong <huzecong@gmail.com>"]
edition = "2018"

[dependencies]
enum_derive = "0.1.7"
macro-attr = "0.2.0"
custom_derive = "0.1.7"
itertools = "0.6.5"
